{{- if .Values.kubeScheduler.managed }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:kubeScheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["{{ template "topolvm.fullname" . }}-kubescheduler"]
{{- end }}
