{{- if .Values.kubeScheduler.managed }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "topolvm.fullname" . }}-kubescheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
{{ toYaml .Values.kubeScheduler.config | indent 4 }}
{{- end }}
