{{- if .Values.kubeScheduler.managed }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "topolvm.fullname" . }}-kubescheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
{{- end }}
