{{- if and .Values.podSecurityPolicy.create .Values.lvmd.managed }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - 'configMap'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/run/topolvm"
      readOnly: false
  hostNetwork: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
{{- end }}
